language: go
go:
  - 1.2
  - tip

before_install:
  - export PATH=$HOME/gopath/bin:$PATH
  - go install -race std
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/kr/godep
  - wget https://github.com/coreos/etcd/releases/download/v0.3.0/etcd-v0.3.0-linux-amd64.tar.gz
  - tar xvzf etcd-v0.3.0-linux-amd64.tar.gz
  - mv etcd-v0.3.0-linux-amd64/etcd $HOME/gopath/bin
  - cd $HOME/gopath/src/github.com/flynn
  - git clone https://github.com/flynn/discoverd
  - cd discoverd
  - godep go install
  - cd ../go-discoverd
  - rm -rf /tmp/godep ../discoverd

install: true

env:
  - DEBUG=1

script:
  - godep go test -race
  - godep go test ./balancer -race
  - godep go test -cover
  - godep go test ./balancer -cover

notifications:
  irc:
    channels:
      - "chat.freenode.net#flynn"
    use_notice: true
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch} - %{commit}: %{message} %{build_url}"

matrix:
  allow_failures:
    - go: tip
